### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by lxsyz** [yasharhezaveh/Ensai#2]
Excuse me, I am a student fo software engineering.And recently I have read your paper and downloaded the code to run.The quick_demo can be run successfully, however, if I use Pycharm to run this code,there are many syntax errors and bugs in the file named "get_data.py".For example:
`np.conj(np.fliplr(np.flipud(Fmap[Npix_2p1 - 1, 1:Npix_2 - 1].reshape((-1, 1))))).shape
`
Fmap is an array.[Npix_2p1 - 1, 1: Npix_2 - 1] , this will return an error.Hope you can help me, I just want to learn these models to build me up.

**Comment by yasharhezaveh** [comment]
Hi,

if you manage to run the quick_demo then there should be no problem in get_data because it is explicitly called and used in quick_demo. 
I suspect your problem has something to do with your Pycharm environment.  I'm not sure what, because I'm not familiar with Pycharm. 
Can you try running things in a regular python command-line environment?
Also, I know that things run smoothly on miniconda. Give that a try?

Another thing that would help is if you copy pasted the full error message here.

**Comment by lxsyz** [comment]
Hi,
Thanks for your prompt, I just find that my python environment is 3.5.And I need to use // instead of / to make the data divisible.Thank you very much.In addition, I think your environment is 2.7.How do you run the Tensorflow?Doesn't it need the Python 3.5?

**Comment by yasharhezaveh** [comment]
yes. This was developed in 2.7
No, tensorflow works fine in  2.7. I assume this is resolved. thanks.
